import assert from 'node:assert/strict';
import {montarBoletim} from './index.ts';
const b=montarBoletim('Boletim <teste>',[{titulo:'<script>alert(1)</script>',subtitulo:'Pesquisa & equipe',texto:'Linha 1\nLinha 2'}],'https://example.test/descadastrar?t=123');
assert.ok(!b.html.includes('<script>'));
assert.ok(b.html.includes('&lt;script&gt;'));
assert.ok(b.html.includes('Pesquisa &amp; equipe'));
assert.ok(b.html.includes('Descadastrar da comunidade'));
assert.ok(b.texto.includes('https://example.test/descadastrar?t=123'));
assert.ok(!montarBoletim('Interno',[]).html.includes('Descadastrar da comunidade'));
assert.ok(b.html.includes('logo-imagotipo-cortex-dark.png'));
assert.ok(b.html.includes('Boletim &lt;teste&gt;'));
assert.ok(b.html.includes('Linha 1<br>Linha 2'));
assert.ok(!b.html.includes(' · '));
const c=montarBoletim('X',[{titulo:'T',subtitulo:'',texto:'t',imagem:'https://e.test/a.png?x="1"'},{titulo:'U',subtitulo:'',texto:'u',imagem:'javascript:alert(1)'}]);
assert.ok(c.html.includes('src="https://e.test/a.png?x=&quot;1&quot;"'));
assert.ok(!c.html.includes('javascript:'));
console.log('11 verificações de newsletter passaram.');
