\set ON_ERROR_STOP on
\pset pager off
-- ============================================================
-- Teste da 2.18.0: a folha única de check-in, os papéis por grupo
-- (com a ficha e a conta bloqueada), o card espelhado e as
-- notificações por tipo.
-- Rode num banco feito do tbase do LEIAME (esqueleto, Storage e a
-- 15.0 à 24.0): o teste aplica o resto (Vault, 25.0 à 32.0, 2.17.0),
-- recria as políticas de produção da ficha, aplica a 2.18.0 e, no fim,
-- a 2.18.0 de novo.
-- ============================================================
create or replace function ok(cond boolean, txt text) returns void language plpgsql as $$
begin
  if cond then raise notice '  ok   %', txt;
  else raise exception 'FALHOU: %', txt; end if;
end $$;
create or replace function eu(p_reg integer, p_papel text) returns void language plpgsql as $$
begin
  perform set_config('teste.registro', coalesce(p_reg::text, ''), false);
  perform set_config('teste.papel', p_papel, false);
  perform set_config('teste.uid', coalesce((select id::text from perfis where registro = p_reg), ''), false);
end $$;
create or replace function gid(p_nome text) returns integer language sql as $$
  select id from grupos where nome = p_nome $$;
create or replace function atv(p_cod text) returns uuid language sql as $$
  select id from atividades where codigo = p_cod $$;

-- o resto das migrações, em ordem
\ir esqueleto_vault.sql
\ir ../v25_documentos_eventos.sql
\ir ../v26_formularios.sql
\ir ../v27_cofre.sql
\ir esqueleto_agenda.sql
\ir ../v28_agenda.sql
create table if not exists presencas (id bigint generated by default as identity primary key,
  registro integer not null, registrado_em timestamptz not null default now());
\ir ../v29_presenca_e_inicio.sql
\ir ../v30_emails.sql
\ir esqueleto_ps.sql
\ir ../v31_ps_entrevistas.sql
\ir ../v32_fila_e_notificacoes.sql
\ir ../2.17.0_notas_fotos_e_cartoes.sql

-- ------------------------------------------------------------
-- A produção como estava (PRODUCAO.md): a ficha aberta a qualquer
-- conta, membros lido por todos, e uma tabela que o anon usa.
-- ------------------------------------------------------------
create table if not exists avaliacoes (id uuid primary key default gen_random_uuid(),
  registro integer not null references membros(registro) on delete cascade, ciclo text, data date default current_date,
  assiduidade integer, comprometimento integer, apontamentos text, encaminhar_pessoal boolean default false,
  tratado boolean default false, responsavel text);
alter table acessos_concedidos enable row level security;
alter table avaliacoes enable row level security;
alter table dados_pessoais enable row level security;
alter table ocorrencias enable row level security;
alter table membros enable row level security;
drop policy if exists acessos_select on acessos_concedidos;
create policy acessos_select on acessos_concedidos for select to authenticated using (true);
drop policy if exists acessos_write on acessos_concedidos;
create policy acessos_write on acessos_concedidos for all to authenticated
  using (papel_atual() in ('admin','pessoal')) with check (papel_atual() in ('admin','pessoal'));
drop policy if exists aval_select on avaliacoes;
create policy aval_select on avaliacoes for select to authenticated using (true);
drop policy if exists aval_insert on avaliacoes;
create policy aval_insert on avaliacoes for insert to authenticated with check (true);
drop policy if exists aval_update on avaliacoes;
create policy aval_update on avaliacoes for update to authenticated
  using (papel_atual() in ('admin','pessoal')) with check (papel_atual() in ('admin','pessoal'));
drop policy if exists dados_all on dados_pessoais;
create policy dados_all on dados_pessoais for all to authenticated
  using (papel_atual() in ('admin','pessoal')) with check (papel_atual() in ('admin','pessoal'));
drop policy if exists ocorr_select on ocorrencias;
create policy ocorr_select on ocorrencias for select to authenticated using (true);
drop policy if exists ocorr_insert on ocorrencias;
create policy ocorr_insert on ocorrencias for insert to authenticated with check (true);
drop policy if exists ocorr_delete on ocorrencias;
create policy ocorr_delete on ocorrencias for delete to authenticated using (papel_atual() in ('admin','pessoal'));
drop policy if exists membros_ler on membros;
create policy membros_ler on membros for select to authenticated using (true);
-- as tabelas das migrações antigas (aplicadas/) com as políticas como
-- estão lá: só o mínimo para a troca de texto da lista de escrita
create table if not exists okr_objetivos (id serial primary key, titulo text, responsaveis integer[] default '{}');
create table if not exists okr_comentarios (id serial primary key, texto text);
create table if not exists portal_avisos (id serial primary key, titulo text, publicado boolean default false,
  data_inicio date, data_fim date);
create table if not exists portal_documentos (id serial primary key, titulo text, publicado boolean default false);
create table if not exists site_projetos (id serial primary key, titulo text);
alter table okr_objetivos enable row level security;
alter table okr_comentarios enable row level security;
alter table portal_avisos enable row level security;
alter table portal_documentos enable row level security;
alter table site_projetos enable row level security;
alter table evento_tipos enable row level security;
create or replace function public.okr_pode_atualizar(r integer[])
returns boolean language sql stable security definer
set search_path = public
as $$
  select public.papel_atual() in ('admin','pessoal')
      or exists (select 1 from public.perfis p
                  where p.id = auth.uid() and p.registro = any(r));
$$;
drop policy if exists okr_select on okr_objetivos;
create policy okr_select on okr_objetivos for select to authenticated using (true);
drop policy if exists okr_insert on okr_objetivos;
create policy okr_insert on okr_objetivos for insert to authenticated
  with check (public.papel_atual() in ('admin','pessoal'));
drop policy if exists okr_delete on okr_objetivos;
create policy okr_delete on okr_objetivos for delete to authenticated
  using (public.papel_atual() in ('admin','pessoal'));
drop policy if exists okrcom_delete on okr_comentarios;
create policy okrcom_delete on okr_comentarios for delete to authenticated
  using (public.papel_atual() in ('admin','pessoal'));
drop policy if exists pavisos_select on portal_avisos;
create policy pavisos_select on portal_avisos for select to authenticated
  using (
    public.papel_atual() in ('admin','pessoal')
    or (publicado
        and (data_inicio is null or data_inicio <= (now() at time zone 'America/Sao_Paulo')::date)
        and (data_fim    is null or data_fim    >= (now() at time zone 'America/Sao_Paulo')::date))
  );
drop policy if exists pavisos_write on portal_avisos;
create policy pavisos_write on portal_avisos for all to authenticated
  using (public.papel_atual() in ('admin','pessoal'))
  with check (public.papel_atual() in ('admin','pessoal'));
drop policy if exists pdocs_select on portal_documentos;
create policy pdocs_select on portal_documentos for select to authenticated
  using (publicado or public.papel_atual() in ('admin','pessoal'));
drop policy if exists pdocs_write on portal_documentos;
create policy pdocs_write on portal_documentos for all to authenticated
  using (public.papel_atual() in ('admin','pessoal'))
  with check (public.papel_atual() in ('admin','pessoal'));
drop policy if exists evtipos_write on evento_tipos;
create policy evtipos_write on evento_tipos for all to authenticated
  using (public.papel_atual() in ('admin','pessoal'))
  with check (public.papel_atual() in ('admin','pessoal'));
drop policy if exists siteprj_write on site_projetos;
create policy siteprj_write on site_projetos for all to authenticated
  using (public.papel_atual() in ('admin','pessoal'))
  with check (public.papel_atual() in ('admin','pessoal'));
insert into portal_avisos (titulo, publicado) values ('Rascunho', false);
create table if not exists rsvp_teste (id serial primary key, x text);
alter table rsvp_teste enable row level security;
drop policy if exists rsvp_anon on rsvp_teste;
create policy rsvp_anon on rsvp_teste for all to anon, authenticated using (true) with check (true);

-- ------------------------------------------------------------
-- As pessoas e os grupos
--   4  Ana      admin (conta), Órtese e Gestão (Gestão é reservado)
--   11 Bruno    leitura, Sinais
--   17 Carla    pessoal pela conta (legado), Órtese
--   23 Diego    leitura, Comunicação
--   40 Fábio    pessoal pelo grupo NRO_PESSOAL
--   41 Gabi     seleção por NRO_PS_ENTREVISTAS, abaixo de NRO_PS
--   42 Hugo     liderança por NRO_LEADERSHIP, e Sinais
--   43 Iara     liderança por NRO_MANAGERS, abaixo de NRO_LEADERSHIP, e NRO_PS
--   44 Jonas    Desligado (a conta diz pessoal e está em NRO_PESSOAL)
--   45 Kátia    Egresso;  46 Lia  Sob demanda
--   47 Mateus   leitura, Órtese e Sinais
-- ------------------------------------------------------------
insert into membros (registro, nome, grupos, status) values
  (40, 'Fábio Souza',  '{NRO_PESSOAL}', 'Ativo'),
  (41, 'Gabi Lins',    '{NRO_PS_ENTREVISTAS}', 'Ativo'),
  (42, 'Hugo Reis',    '{NRO_LEADERSHIP,Sinais}', 'Ativo'),
  (43, 'Iara Melo',    '{NRO_MANAGERS,NRO_PS}', 'Em pausa / avaliação'),
  (44, 'Jonas Prado',  '{NRO_PESSOAL,Órtese}', 'Desligado'),
  (45, 'Kátia Dias',   '{Órtese}', 'Egresso'),
  (46, 'Lia Moura',    '{Órtese}', 'Sob demanda'),
  (47, 'Mateus Cruz',  '{Órtese,Sinais}', 'Ativo')
on conflict (registro) do nothing;
insert into grupos (nome, prefixo, ordem) values
  ('NRO_PESSOAL','NPE',1), ('NRO_PS','NPS',2), ('NRO_PS_ENTREVISTAS','NPSE',3),
  ('NRO_LEADERSHIP','NLD',4), ('NRO_MANAGERS','NMG',5)
on conflict (nome) do nothing;
update grupos set pai_id = gid('NRO_PS') where nome = 'NRO_PS_ENTREVISTAS';
update grupos set pai_id = gid('NRO_LEADERSHIP') where nome = 'NRO_MANAGERS';
update grupos set reservado = true where nome = 'Gestão';
insert into perfis (id, email, papel, registro) values
  ('00000000-0000-0000-0000-000000000004', 'ana@nro.dev',    'admin',   4),
  ('00000000-0000-0000-0000-000000000011', 'bruno@nro.dev',  'leitura', 11),
  ('00000000-0000-0000-0000-000000000017', 'carla@nro.dev',  'pessoal', 17),
  ('00000000-0000-0000-0000-000000000023', 'diego@nro.dev',  'leitura', 23),
  ('00000000-0000-0000-0000-000000000040', 'fabio@nro.dev',  'leitura', 40),
  ('00000000-0000-0000-0000-000000000041', 'gabi@nro.dev',   'leitura', 41),
  ('00000000-0000-0000-0000-000000000042', 'hugo@nro.dev',   'leitura', 42),
  ('00000000-0000-0000-0000-000000000043', 'iara@nro.dev',   'leitura', 43),
  ('00000000-0000-0000-0000-000000000044', 'jonas@nro.dev',  'pessoal', 44),
  ('00000000-0000-0000-0000-000000000045', 'katia@nro.dev',  'leitura', 45),
  ('00000000-0000-0000-0000-000000000046', 'lia@nro.dev',    'leitura', 46),
  ('00000000-0000-0000-0000-000000000047', 'mateus@nro.dev', 'leitura', 47),
  ('00000000-0000-0000-0000-0000000000ff', 'tecnica@nro.dev', 'admin',  null)
on conflict (id) do nothing;

-- os cartões: um em cada quadro
insert into atividades (codigo, grupo_id, seq, titulo, criado_por) values
  ('ORT-1', gid('Órtese'), 1, 'Molde da órtese', 4),
  ('ORT-2', gid('Órtese'), 2, 'Teste de bancada', 4),
  ('SIN-1', gid('Sinais'), 1, 'Filtro do EMG', 11),
  ('GES-1', gid('Gestão'), 1, 'Orçamento do semestre', 4)
on conflict (codigo) do nothing;

-- a ficha: um de cada para Bruno
insert into dados_pessoais (registro, curso) values (11, 'Engenharia') on conflict do nothing;
insert into avaliacoes (registro, ciclo, assiduidade) values (11, '2026/2', 4);
insert into ocorrencias (registro, tipo, descricao) values (11, 'Advertência', 'Faltou à reunião');
insert into acessos_concedidos (registro, item_id) select 11, id from itens_de_acesso limit 1;

-- duas folhas ativas, como a 29.0 permitia
select eu(4, 'admin');
insert into checkin_folhas (rotulo, criada_por) values ('Porta', 'x'), ('Recepção', 'x');

-- as preferências de e-mail como estavam (16.0): Bruno escolheu resumo,
-- Diego nunca, Mateus escolheu imediato (salvou depois da baixa); Fábio
-- só tem a linha que a baixa criou (imediato, sem escolha); Hugo, nada
insert into notificacao_preferencias (registro, email_modo, ultimo_email, atualizado_em) values
  (11, 'resumo',   null, now() - interval '9 days'),
  (23, 'nunca',    now() - interval '3 days', now() - interval '2 days'),
  (47, 'imediato', now() - interval '5 days', now() - interval '1 day'),
  (40, 'imediato', now() - interval '4 days', now() - interval '4 days')
on conflict (registro) do nothing;
update membros set email_nro = lower(split_part(nome, ' ', 1)) || '@nro.dev' where email_nro is null;

\ir ../2.18.0_soma.sql

-- ============================================================
-- Check-in: folha única
-- ============================================================
do $$
declare r jsonb; v_a uuid; v_b uuid; v_tok_a uuid; v_tok_b uuid;
begin
  raise notice 'Check-in: folha única';
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'a migração deixou uma folha ativa só');
  perform ok((select rotulo from checkin_folhas where revogada_em is null) = 'Recepção', 'a mais recente');

  perform eu(11, 'leitura');
  perform ok(checkin_folha_criar('x')->>'status' = 'sem_permissao', 'quem é leitura não gera');
  perform eu(17, 'pessoal');
  perform ok(checkin_folha_criar('x')->>'status' = 'sem_permissao', 'o Depto. de Pessoal também não gera');
  perform ok(checkin_folha_revogar(gen_random_uuid())->>'status' = 'sem_permissao', 'nem revoga');

  perform eu(4, 'admin');
  select token into v_tok_a from checkin_folhas where revogada_em is null;
  r := checkin_folha_criar('Entrada');
  perform ok(r->>'status' = 'ok' and r->>'token' is not null, 'admin gera e recebe o token');
  v_b := (r->>'id')::uuid; v_tok_b := (r->>'token')::uuid;
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'continua uma só ativa');
  perform ok((select revogada_em is null from checkin_folhas where id = v_b), 'a nova é a ativa');
  perform ok((select revogada_motivo from checkin_folhas where token = v_tok_a) = 'substituída', 'a anterior foi invalidada');
  perform ok((select baixada_em is not null and baixada_por is not null from checkin_folhas where id = v_b), 'o download fica registrado');

  perform eu(11, 'leitura');
  perform ok(registrar_checkin_folha(v_tok_a)->>'status' = 'folha_invalida', 'o QR antigo é recusado');
  perform ok(registrar_checkin_folha(v_tok_b)->>'status' = 'ok', 'o QR novo registra');

  perform eu(4, 'admin');
  perform ok(checkin_folha_revogar(v_b)->>'status' = 'ok', 'admin revoga a ativa');
  perform ok(checkin_folha_criar('Depois')->>'status' = 'ok', 'e gera outra depois');
end $$;

-- ============================================================
-- Papéis por grupo
-- ============================================================
do $$
begin
  raise notice 'Papéis por grupo: a semente e os papéis de cada um';
  perform ok((select count(*) from grupo_papeis) = 3, 'a semente pôs três grupos');
  perform ok((select papel from grupo_papeis where grupo_id = gid('NRO_PESSOAL')) = 'pessoal', 'NRO_PESSOAL é pessoal (pelo nome, não pela chave)');
  perform ok((select papel from grupo_papeis where grupo_id = gid('NRO_PS')) = 'selecao', 'NRO_PS é seleção');
  perform ok((select papel from grupo_papeis where grupo_id = gid('NRO_LEADERSHIP')) = 'lideranca', 'NRO_LEADERSHIP é liderança');

  perform eu(4, 'x');
  perform ok(papeis_atuais() = '{admin,leitura}' and papel_atual() = 'admin', 'Ana: admin pela conta');
  perform eu(null, 'x'); perform set_config('teste.uid', '00000000-0000-0000-0000-0000000000ff', false);
  perform ok(papel_atual() = 'admin' and conta_ativa() and portal_registro_atual() is null, 'conta técnica sem registro continua admin');
  perform eu(11, 'x');
  perform ok(papeis_atuais() = '{leitura}' and papel_atual() = 'leitura', 'Bruno: leitura');
  perform eu(17, 'x');
  perform ok(papel_atual() = 'pessoal', 'Carla: pessoal pela conta (legado da transição)');
  perform eu(40, 'x');
  perform ok(papeis_atuais() = '{pessoal,leitura}' and papel_atual() = 'pessoal', 'Fábio: pessoal pelo grupo');
  perform eu(41, 'x');
  perform ok(papel_atual() = 'selecao', 'Gabi: seleção por um subgrupo de NRO_PS');
  perform eu(42, 'x');
  perform ok(papel_atual() = 'lideranca', 'Hugo: liderança pelo grupo');
  perform eu(43, 'x');
  perform ok(papeis_atuais() = '{lideranca,selecao,leitura}', 'Iara: liderança pelo subgrupo e seleção, em ordem');
  perform ok(tenho_papel('selecao') and tenho_papel('lideranca') and not tenho_papel('pessoal'), 'tenho_papel olha a lista, não só o mais forte');
  perform eu(23, 'x');
  perform ok(not tenho_papel('selecao') and tenho_papel('leitura'), 'Diego só lê');
  perform eu(4, 'x');
  perform ok(tenho_papel('lideranca') and tenho_papel('selecao'), 'admin tem todos');

  raise notice 'Papéis por grupo: conta bloqueada';
  perform eu(44, 'x');
  perform ok(papeis_atuais() = '{}' and papel_atual() = 'nenhum', 'Jonas, desligado: nenhum papel, mesmo com a conta e o grupo de pessoal');
  perform ok(portal_registro_atual() is null and not conta_ativa(), 'e sem registro, conta inativa');
  perform ok(meu_nivel_no_grupo(gid('Órtese')) = 'nenhum', 'nem o quadro do grupo dele');
  perform ok(atividade_comentar(jsonb_build_object('atividade_id', atv('ORT-1'), 'corpo', 'oi'))->>'status' = 'sem_registro', 'nem comenta');
  perform ok(grupo_salvar(jsonb_build_object('nome','X'))->>'status' = 'sem_permissao', 'nem passa pelo "not in" das funções de gestão');
  perform eu(45, 'x');
  perform ok(papel_atual() = 'nenhum' and portal_registro_atual() is null, 'Kátia, egresso: nada');
  perform eu(46, 'x');
  perform ok(papel_atual() = 'nenhum' and portal_registro_atual() is null, 'Lia, sob demanda: nada');
  perform set_config('teste.uid', '', false);
  perform ok(papel_atual() = 'nenhum' and papeis_atuais() = '{}', 'sem sessão: nenhum, nunca nulo');
end $$;

-- ------------------------------------------------------------
-- Quadros: a regra por papel
-- ------------------------------------------------------------
do $$
begin
  raise notice 'Papéis por grupo: quadros';
  perform eu(40, 'x');
  perform ok(meu_nivel_no_grupo(gid('Sinais')) = 'edicao' and meu_nivel_no_grupo(gid('Gestão')) = 'edicao', 'pessoal pelo grupo edita todo quadro');
  perform eu(42, 'x');
  perform ok(meu_nivel_no_grupo(gid('Sinais')) = 'edicao', 'liderança edita o quadro do grupo dela');
  perform ok(meu_nivel_no_grupo(gid('Órtese')) = 'leitura', 'e lê o dos outros');
  perform ok(meu_nivel_no_grupo(gid('Gestão')) = 'leitura', 'até o reservado');
  perform ok(atividade_editar(jsonb_build_object('id', atv('ORT-1'), 'titulo', 'x'))->>'status' = 'sem_permissao', 'mas não escreve no quadro alheio');
  perform ok(atividade_comentar(jsonb_build_object('atividade_id', atv('ORT-1'), 'corpo', 'x'))->>'status' = 'sem_permissao', 'nem comenta nele');
  perform ok(atividade_editar(jsonb_build_object('id', atv('SIN-1'), 'prioridade', 'alta'))->>'status' = 'ok', 'no seu quadro edita');
  perform eu(43, 'x');
  perform ok(meu_nivel_no_grupo(gid('Gestão')) = 'leitura' and meu_nivel_no_grupo(gid('NRO_LEADERSHIP')) = 'edicao', 'liderança por subgrupo: lê tudo, edita o grupo de cima');
  perform eu(11, 'x');
  perform ok(meu_nivel_no_grupo(gid('Gestão')) = 'nenhum' and meu_nivel_no_grupo(gid('Órtese')) = 'leitura', 'leitura: nada no reservado, lê o comum');
  perform eu(41, 'x');
  perform ok(meu_nivel_no_grupo(gid('Gestão')) = 'nenhum', 'seleção também não vê o reservado');
end $$;

-- ------------------------------------------------------------
-- A lista de escrita da liderança e o que fica fora dela
-- ------------------------------------------------------------
do $$
begin
  raise notice 'Papéis por grupo: a lista de escrita';
  perform eu(42, 'x');
  perform ok(eh_gestao(), 'liderança é gestão');
  perform ok(agenda_gestor() and treinamento_gestor() and doc_gestor() and studio_pode_aprovar() and site_imprensa_editor(),
             'agenda, treinamentos, projetos e arquivos, Studio');
  perform ok(eh_comite(), 'e Seleção');
  perform ok(email_destinatarios(jsonb_build_object('tipo','todos'))->>'status' is distinct from 'sem_permissao', 'e-mails');
  perform ok(not cofre_gestor(), 'cofre não');
  perform ok(grupo_salvar(jsonb_build_object('nome','X'))->>'status' = 'sem_permissao', 'grupos não');
  perform ok(grupo_papel_definir(jsonb_build_object('grupo_id', gid('Sinais'), 'papel', 'selecao'))->>'status' = 'sem_permissao', 'papel de grupo não');
  perform ok(checkin_folha_criar('x')->>'status' = 'sem_permissao', 'folha de check-in não');
  perform ok(contas_papeis()->>'status' = 'sem_permissao', 'contas não');
  perform ok(not agenda_pode_ver(gen_random_uuid()), 'evento fechado alheio continua fechado');

  perform eu(41, 'x');
  perform ok(eh_comite() and not eh_gestao(), 'seleção: comitê, não gestão');
  perform ok(fila_situacao()->>'status' is distinct from 'sem_permissao', 'seleção vê a fila de e-mails');
  perform eu(43, 'x');
  perform ok(fila_situacao()->>'status' is distinct from 'sem_permissao', 'liderança e seleção ao mesmo tempo também');
  perform eu(11, 'x');
  perform ok(not eh_gestao() and not eh_comite() and not agenda_gestor() and not doc_gestor(), 'leitura: nada disso');
  perform ok(fila_situacao()->>'status' = 'sem_permissao', 'nem a fila');
  perform ok(email_programar(jsonb_build_object('assunto','x'))->>'status' = 'sem_permissao', 'nem programa e-mail');

  perform eu(40, 'x');
  perform ok(grupo_papel_definir(jsonb_build_object('grupo_id', gid('Sinais'), 'papel', 'selecao'))->>'status' = 'sem_permissao', 'papel de grupo é só de admin, nem pessoal');
  perform ok((contas_papeis()->'contas') is not null, 'pessoal lê os papéis das contas');
  perform eu(4, 'x');
  perform ok(grupo_papel_definir(jsonb_build_object('grupo_id', gid('Sinais'), 'papel', 'chefe'))->>'status' = 'invalido', 'papel que não existe');
  perform ok(grupo_papel_definir(jsonb_build_object('grupo_id', gid('Sinais'), 'papel', 'selecao'))->>'status' = 'ok', 'admin define');
  perform eu(11, 'x');
  perform ok(papel_atual() = 'selecao', 'e Bruno, de Sinais, vira seleção na hora');
  perform eu(4, 'x');
  perform ok(grupo_papel_definir(jsonb_build_object('grupo_id', gid('Sinais')))->>'status' = 'ok', 'admin tira');
  perform eu(11, 'x');
  perform ok(papel_atual() = 'leitura', 'e Bruno volta a leitura');
  perform eu(4, 'x');
  perform ok((select x->'papeis' @> '[{"papel":"lideranca","via":"NRO_LEADERSHIP"}]'
                from jsonb_array_elements(contas_papeis()->'contas') x where x->>'id' = '00000000-0000-0000-0000-000000000043'),
             'Contas: a liderança de Iara vem "via NRO_LEADERSHIP" (o grupo do papel, mesmo por subgrupo)');
  perform ok((select (x->>'bloqueada')::boolean and x->'papeis' = '[]'
                from jsonb_array_elements(contas_papeis()->'contas') x where x->>'id' = '00000000-0000-0000-0000-000000000044'),
             'Contas: Jonas aparece bloqueado, sem papel');
  perform ok((select x->'papeis' @> '[{"papel":"pessoal","via":"legado"}]'
                from jsonb_array_elements(contas_papeis()->'contas') x where x->>'id' = '00000000-0000-0000-0000-000000000017'),
             'Contas: o pessoal de Carla vem da conta (legado)');
end $$;

-- ------------------------------------------------------------
-- RLS: a ficha, a trava e o anon
-- ------------------------------------------------------------
do $$ declare t text; begin
  for t in select tablename from pg_tables where schemaname = 'public' and tablename <> 'checkin_folhas' loop
    execute format('grant select, insert, update, delete on public.%I to authenticated', t); end loop;
  grant select, insert on rsvp_teste to anon;
  grant usage, select on all sequences in schema public to authenticated, anon;
  grant select on atividades_quadro to authenticated;
end $$;
set role authenticated;
do $$
declare pegou boolean; n integer;
begin
  raise notice 'Papéis por grupo: a ficha';
  perform eu(4, 'x');
  perform ok((select count(*) from ocorrencias) >= 1 and (select count(*) from dados_pessoais) >= 1, 'admin lê ocorrências e dados pessoais');
  perform eu(40, 'x');
  perform ok((select count(*) from ocorrencias) >= 1, 'pessoal pelo grupo lê ocorrências');
  insert into ocorrencias (registro, tipo) values (23, 'Elogio');
  perform ok(true, 'e inclui');
  perform eu(42, 'x');
  perform ok((select count(*) from dados_pessoais) >= 1, 'liderança lê dados pessoais');
  perform ok((select count(*) from avaliacoes) >= 1, 'e avaliações');
  perform ok((select count(*) from acessos_concedidos) >= 1, 'e acessos');
  perform ok((select count(*) from ocorrencias) = 0, 'mas não ocorrências');
  pegou := false;
  begin insert into ocorrencias (registro, tipo) values (11, 'x'); exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem inclui ocorrência');
  pegou := false;
  begin insert into avaliacoes (registro, ciclo) values (11, 'x'); exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem avaliação');
  pegou := false;
  begin update dados_pessoais set curso = 'x' where registro = 11; get diagnostics n = row_count; pegou := n = 0;
  exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem muda dados pessoais');

  perform eu(11, 'x');
  perform ok((select count(*) from ocorrencias) = 0 and (select count(*) from avaliacoes) = 0
             and (select count(*) from acessos_concedidos) = 0 and (select count(*) from dados_pessoais) = 0,
             'leitura não lê nada da ficha (nem a própria)');
  pegou := false;
  begin insert into ocorrencias (registro, tipo) values (23, 'x'); exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem inclui ocorrência (a porta aberta da produção)');
  pegou := false;
  begin insert into avaliacoes (registro, ciclo) values (23, 'x'); exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem avaliação');
  perform ok((select count(*) from membros) > 5, 'a tabela de todos (using true) continua aberta');
  perform ok((select count(*) from portal_avisos) = 0, 'leitura não vê o aviso em rascunho');
  pegou := false;
  begin insert into portal_avisos (titulo) values ('x'); exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'nem publica aviso');

  raise notice 'Papéis por grupo: a lista de escrita pela RLS';
  perform eu(42, 'x');
  perform ok((select count(*) from portal_avisos) = 1, 'liderança vê o aviso em rascunho');
  insert into portal_avisos (titulo) values ('Da liderança');
  insert into okr_objetivos (titulo) values ('Objetivo da liderança');
  insert into portal_documentos (titulo) values ('Doc');
  insert into site_projetos (titulo) values ('Projeto');
  perform ok(true, 'e escreve em avisos, OKRs, documentos e site');
  perform ok(okr_pode_atualizar('{}'), 'e atualiza qualquer OKR');

  raise notice 'Papéis por grupo: conta bloqueada no banco';
  foreach n in array array[44, 45, 46] loop
    perform eu(n, 'x');
    perform ok((select count(*) from membros) = 0 and (select count(*) from atividades) = 0
               and (select count(*) from grupo_papeis) = 0 and (select count(*) from rsvp_teste) = 0,
               format('registro %s: não lê nem o que é de todos', n));
    pegou := false;
    begin insert into rsvp_teste (x) values ('y'); exception when insufficient_privilege then pegou := true; end;
    perform ok(pegou, format('registro %s: nem escreve', n));
  end loop;

  raise notice 'Papéis por grupo: quadros pela RLS';
  perform eu(42, 'x');
  perform ok((select count(*) from atividades_quadro where codigo = 'GES-1') = 1, 'liderança vê o cartão do quadro reservado');
  update atividades set titulo = 'mexi' where codigo = 'ORT-1'; get diagnostics n = row_count;
  perform ok(n = 0, 'e não o altera direto');
  perform eu(11, 'x');
  perform ok((select count(*) from atividades_quadro where codigo = 'GES-1') = 0, 'leitura não vê o reservado');
end $$;
reset role;
set role anon;
do $$ begin
  insert into rsvp_teste (x) values ('anon');
  perform ok((select count(*) from rsvp_teste) >= 1, 'anon: a trava não vale para quem não entrou (rsvp, quiosque)');
end $$;
reset role;

-- ------------------------------------------------------------
-- O apontamento abre ocorrência pela porta própria
-- ------------------------------------------------------------
do $$
declare v_ap uuid; r jsonb;
begin
  raise notice 'Papéis por grupo: apontamento e ocorrência';
  insert into apontamentos (grupo, responsavel, responsavel_id)
  values ('Sinais', 'Bruno', '00000000-0000-0000-0000-000000000011') returning id into v_ap;
  insert into apontamento_itens (apontamento_id, registro, sinalizado, justificativa)
  values (v_ap, 47, true, 'Faltas sem aviso'), (v_ap, 42, false, null);
  perform eu(23, 'x');
  perform ok(apontamento_ocorrencias(v_ap, array[47])->>'status' = 'nao_encontrado', 'quem não fez o apontamento não abre');
  perform eu(11, 'x');
  r := apontamento_ocorrencias(v_ap, array[47, 42]);
  perform ok(r->>'status' = 'ok' and (r->>'abertas')::int = 1, 'quem apontou abre, só para quem foi sinalizado');
  perform ok(exists (select 1 from ocorrencias where registro = 47 and tipo = 'Sinalização reincidente'
                     and descricao = 'Faltas sem aviso'), 'a ocorrência está na ficha');
  perform ok((apontamento_ocorrencias(v_ap, array[47])->>'abertas')::int = 0, 'chamar de novo não repete');
end $$;

-- ============================================================
-- Card espelhado
-- ============================================================
do $$
declare r jsonb; v_sin integer := gid('Sinais'); v_ort integer := gid('Órtese'); v_novo uuid;
begin
  raise notice 'Card espelhado';
  perform eu(42, 'x');
  perform ok(atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_sin))->>'status' = 'sem_permissao',
             'liderança que só escreve no destino não espelha');
  perform eu(11, 'x');
  perform ok(atividade_editar(jsonb_build_object('id', atv('ORT-1'), 'titulo', 'x'))->>'status' = 'sem_permissao',
             'Bruno, de Sinais, não edita ORT-1 antes do espelho');
  perform eu(47, 'x');
  perform ok(atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_ort))->>'status' = 'invalido', 'espelhar no próprio quadro dono, não');
  r := atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_sin));
  perform ok(r->>'status' = 'ok', 'Mateus, que escreve na Órtese e em Sinais, espelha');
  perform ok((atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_sin))->>'status') = 'ok'
             and (select count(*) from atividade_quadros where atividade_id = atv('ORT-1')) = 1, 'espelhar de novo não duplica');
  perform ok((select espelhos = array[v_sin] from atividades_quadro where codigo = 'ORT-1'), 'o quadro mostra o espelho');
  perform ok(exists (select 1 from atividade_log where atividade_id = atv('ORT-1') and tipo = 'espelhou'), 'e o histórico diz');

  perform eu(11, 'x');
  perform ok(atividade_editar(jsonb_build_object('id', atv('ORT-1'), 'titulo', 'Molde da órtese, v2'))->>'status' = 'ok',
             'Bruno, que escreve em um dos quadros ligados, edita');
  perform ok((select titulo from atividades where codigo = 'ORT-1') = 'Molde da órtese, v2', 'é o mesmo registro: a Órtese vê a mudança');
  perform ok(atividade_editar(jsonb_build_object('id', atv('ORT-1'), 'status', 'fazendo', 'ordem', 7, 'quadro', v_sin))->>'status' = 'ok',
             'move na coluna do quadro dele');
  perform ok((select status = 'fazendo' and ordem <> 7 from atividades where codigo = 'ORT-1')
             and (select ordem = 7 from atividade_quadros where atividade_id = atv('ORT-1') and grupo_id = v_sin),
             'o status é um só; a ordem é a de Sinais');
  perform ok(atividade_comentar(jsonb_build_object('atividade_id', atv('ORT-1'), 'corpo', 'Ajustei o molde'))->>'status' = 'ok', 'comenta');
  perform ok(atividade_checklist(jsonb_build_object('acao','lista_criar','atividade_id', atv('ORT-1'), 'titulo','Etapas', 'texto', 'a'))->>'status' = 'ok', 'cria checklist');
  perform ok(atividade_editar(jsonb_build_object('id', atv('ORT-1'), 'arquivada', true))->>'status' = 'sem_permissao', 'mas arquivar é do quadro dono');
  perform ok(atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', gid('Comunicação')))->>'status' = 'sem_permissao',
             'e espelhar em outro pede escrita no dono');

  perform eu(4, 'x');
  perform ok(atividade_espelhar(jsonb_build_object('id', atv('GES-1'), 'grupo_id', v_sin))->>'status' = 'ok', 'admin espelha o cartão do reservado em Sinais');
end $$;
set role authenticated;
do $$ begin
  perform eu(11, 'x');
  perform ok((select count(*) from atividades_quadro where codigo = 'GES-1') = 1, 'Bruno vê GES-1 pelo espelho');
  perform ok((select count(*) from atividade_comentarios c join atividades a on a.id = c.atividade_id where a.codigo = 'ORT-1') >= 1,
             'e os comentários de ORT-1');
  perform ok((select count(*) from atividade_quadros) >= 2, 'e os espelhos');
  perform eu(23, 'x');
  perform ok((select count(*) from atividades_quadro where codigo = 'GES-1') = 1,
             'Diego, que só lê Sinais, também vê GES-1: espelhar num quadro aberto abre o cartão');
  perform eu(42, 'x');
  perform ok((select espelhos from atividades_quadro where codigo = 'GES-1') = array[gid('Sinais')], 'liderança vê o cartão e o espelho');
end $$;
reset role;
do $$
declare r jsonb; v_sin integer := gid('Sinais'); v_com integer := gid('Comunicação');
begin
  perform eu(11, 'x');
  perform ok(atividade_espelho_remover(jsonb_build_object('id', atv('GES-1'), 'grupo_id', v_sin))->>'status' = 'ok',
             'quem escreve no quadro espelho tira o espelho');
  perform ok(not exists (select 1 from atividade_quadros where atividade_id = atv('GES-1')), 'e ele some');
  perform eu(23, 'x');
  perform ok(atividade_espelho_remover(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_sin))->>'status' in ('sem_permissao','nao_encontrado'),
             'quem não escreve em nenhum dos dois não tira');

  -- mover: o novo no destino, o original arquivado, os espelhos vão junto
  perform eu(4, 'x');
  perform ok(atividade_espelhar(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_com))->>'status' = 'ok', 'admin espelha em Comunicação também');
  r := atividade_mover(jsonb_build_object('id', atv('ORT-1'), 'grupo_id', v_sin));
  perform ok(r->>'status' = 'ok', 'admin move ORT-1 para Sinais');
  perform ok((select arquivada from atividades where codigo = 'ORT-1'), 'o original fica arquivado');
  perform ok((select grupo_id = v_sin and espelhos = array[v_com] from atividades_quadro where codigo = r->>'codigo'),
             'o novo é de Sinais e continua espelhado em Comunicação (o de Sinais virou o dono)');
  perform ok(not exists (select 1 from atividade_quadros where atividade_id = atv('ORT-1')), 'o original não tem mais espelho');
end $$;

-- ------------------------------------------------------------
-- O custo: o quadro inteiro, lido pela liderança
-- ------------------------------------------------------------
insert into atividades (codigo, grupo_id, seq, titulo)
select 'CARGA-' || i, gid(case i % 3 when 0 then 'Órtese' when 1 then 'Sinais' else 'Gestão' end), 1000 + i, 'Cartão ' || i
  from generate_series(1, 3000) i;
analyze;
set role authenticated;
select eu(42, 'x');
\o /dev/null
explain analyze select * from atividades_quadro where not arquivada;
\o
do $$
declare t0 timestamptz; ms numeric; n integer;
begin
  perform eu(42, 'x');
  t0 := clock_timestamp();
  select count(*), sum(comentarios + check_total + cardinality(espelhos)) into n, ms
    from atividades_quadro where not arquivada;
  ms := extract(epoch from clock_timestamp() - t0) * 1000;
  raise notice '  custo: % cartões lidos pela liderança em % ms', n, round(ms);
  perform ok(n >= 3000, 'a liderança lê os 3000 cartões de três quadros');
  perform ok(ms < 1500, 'em menos de 1,5 s (as regras do quadro rodam uma vez por consulta, não por cartão)');
end $$;
reset role;

-- ------------------------------------------------------------
-- Notificações por tipo
-- ------------------------------------------------------------
do $$
declare r jsonb; n integer;
begin
  raise notice 'Notificações por tipo: categorias e migração';
  perform ok(jsonb_array_length(notificacao_categorias()) = 9, 'nove categorias');
  perform ok(notificacao_categoria('atividade_atribuida') = 'atividades' and notificacao_categoria('quadro_liberado') = 'atividades'
             and notificacao_categoria('projeto_equipe') = 'atividades', 'atividades: atividade_*, quadro_liberado, projeto_equipe');
  perform ok(notificacao_categoria('feedback_novo') = 'bugs_melhorias' and notificacao_categoria('doc_revisao') = 'documentos'
             and notificacao_categoria('studio_decisao') = 'studio' and notificacao_categoria('reporte_prazo') = 'reporte'
             and notificacao_categoria('agenda_convite') = 'agenda' and notificacao_categoria('evento_ext') = 'agenda'
             and notificacao_categoria('pessoal_ocorrencia') = 'pessoal' and notificacao_categoria('solicitacao_respondida') = 'pessoal'
             and notificacao_categoria('treinamento') = 'treinamentos' and notificacao_categoria('cofre_troca') = 'sistema',
             'os demais tipos nas suas categorias');
  perform ok(notificacao_categoria('teste_email') is null and notificacao_categoria('teste_push') is null, 'os testes de envio ficam fora');
  perform ok((select count(*) from notificacao_canais where registro = 11 and email = 'diario' and push) = 9, 'resumo vira diário em todas');
  perform ok((select count(*) from notificacao_canais where registro = 23 and email = 'nunca') = 9, 'nunca continua nunca');
  perform ok((select count(*) from notificacao_canais where registro = 47 and email = 'instantaneo') = 9, 'imediato escolhido vira instantâneo');
  perform ok(not exists (select 1 from notificacao_canais where registro in (40, 42)), 'a linha da baixa e quem não tinha nada ficam no padrão');
  perform ok(notificacao_canal_email(40, 'doc_revisao') = 'semanal' and notificacao_canal_push(40, 'doc_revisao'), 'padrão: semanal e push');
  perform ok(notificacao_canal_email(23, 'teste_email') = 'instantaneo', 'o teste de e-mail sai na hora mesmo com nunca');
  perform ok(notificacao_resumo_marco('diario', '2026-10-07 10:00-03') = '2026-10-07 08:00-03'
             and notificacao_resumo_marco('diario', '2026-10-07 07:00-03') = '2026-10-06 08:00-03', 'o marco diário: o último 8h');
  perform ok(notificacao_resumo_marco('semanal', '2026-10-07 10:00-03') = '2026-10-05 08:00-03'
             and notificacao_resumo_marco('semanal', '2026-10-05 07:59-03') = '2026-09-28 08:00-03', 'o semanal: a última segunda às 8h');

  raise notice 'Notificações por tipo: a tela';
  perform eu(42, 'x');
  r := notificacao_canais_meus();
  perform ok(r->>'status' = 'ok' and jsonb_array_length(r->'categorias') = 9
             and (select bool_and((c->>'push')::boolean and c->>'email' = 'semanal') from jsonb_array_elements(r->'categorias') c),
             'sem linha, a tela mostra o padrão');
  perform ok(r->'categorias'->0->>'chave' = 'atividades' and r->'categorias'->0->>'nome' = 'Atividades', 'na ordem, com o nome');
  r := notificacao_canais_salvar('{"canais":[{"categoria":"atividades","push":false,"email":"instantaneo"},
                                             {"categoria":"studio","push":true,"email":"nunca"},
                                             {"categoria":"documentos","push":true,"email":"semanal"}]}');
  perform ok(r->>'status' = 'ok', 'salvar');
  perform ok((select count(*) from notificacao_canais where registro = 42) = 2, 'o que é igual ao padrão não vira linha');
  perform ok(notificacao_canal_email(42, 'atividade_mencao') = 'instantaneo' and not notificacao_canal_push(42, 'atividade_mencao')
             and notificacao_canal_email(42, 'studio_decisao') = 'nunca', 'e vale para os tipos da categoria');
  r := notificacao_canais_salvar('{"canais":[{"categoria":"atividades","email":"hora_em_hora"}]}');
  perform ok(r->>'status' = 'invalido' and r->>'campo' = 'email', 'frequência desconhecida é recusada');
  r := notificacao_canais_salvar('{"canais":[{"categoria":"convites","email":"nunca"}]}');
  perform ok(r->>'status' = 'invalido' and r->>'campo' = 'categoria', 'categoria desconhecida também (convites e pílulas não são configuráveis)');
  perform eu(null, 'admin');
  perform ok(notificacao_canais_salvar('{"canais":[]}')->>'status' = 'sem_registro', 'conta sem registro: sem_registro');
  perform eu(46, 'x');
  perform ok(notificacao_canais_meus()->>'status' = 'sem_registro', 'conta bloqueada não tem preferência a mexer');
  perform eu(40, 'x');
  r := notificacao_preferencia_salvar('{"email_modo":"resumo"}');
  perform ok(r->>'status' = 'ok'
             and (select count(*) from notificacao_canais where registro = 40 and email = 'diario') = 9,
             'a função antiga (tela em cache) aplica o modo a todas as categorias');
  r := notificacao_canais_salvar(jsonb_build_object('canais', (select jsonb_agg(jsonb_build_object('categoria', c->>'chave'))
             from jsonb_array_elements(notificacao_categorias()) c)));
  perform ok(r->>'status' = 'ok'
             and not exists (select 1 from notificacao_canais where registro = 40), 'voltar ao padrão apaga as linhas');
end $$;

-- os avisos: um pouco antes do marco e agora
delete from notificacoes;
insert into notificacao_canais (registro, categoria, email) values (46, 'atividades', 'instantaneo') on conflict do nothing;
insert into notificacoes (registro, tipo, titulo, criado_em) values
  (42, 'atividade_atribuida', 'H1 atribuída',  now()),
  (42, 'studio_decisao',      'H2 studio',     now()),
  (42, 'doc_revisao',         'H3 doc antigo', notificacao_resumo_marco('semanal') - interval '1 hour'),
  (42, 'feedback_novo',       'H4 bug',        now()),
  (11, 'feedback_novo',       'B1 bug ontem',  notificacao_resumo_marco('diario') - interval '1 hour'),
  (11, 'doc_aprovada',        'B2 doc agora',  now()),
  (11, 'atividade_prazo',     'B3 velho',      now() - interval '3 days'),
  (23, 'atividade_mencao',    'D1 nunca',      now()),
  (23, 'teste_email',         'D2 teste',      now()),
  (40, 'studio_lembrete',     'F1 lembrete',   now()),
  (40, 'doc_revisao',         'F2 doc agora',  now()),
  (47, 'cofre_troca',         'M1 cofre',      now() - interval '4 days'),
  (46, 'atividade_atribuida', 'L1 bloqueada',  now()),
  (45, 'atividade_atribuida', 'K1 egressa',    now());
insert into push_inscricoes (registro, endpoint, p256dh, auth) values
  (42, 'https://push.exemplo/hugo', repeat('a', 87), repeat('b', 22)),
  (46, 'https://push.exemplo/lia',  repeat('a', 87), repeat('c', 22))
on conflict (endpoint) do nothing;
update push_inscricoes set criado_em = now() - interval '2 days';

do $$
declare l jsonb; t text[]; ids bigint[]; pu jsonb;
begin
  raise notice 'Notificações por tipo: o lote de e-mail';
  l := notificacoes_email_lote(200);
  select array_agg(i->>'titulo' order by i->>'titulo') into t
    from jsonb_array_elements(l) d, jsonb_array_elements(d->'itens') i;
  perform ok('H1 atribuída' = any(t), 'instantâneo sai na hora');
  perform ok(not ('H2 studio' = any(t)), 'categoria com e-mail desligado não sai');
  perform ok('H3 doc antigo' = any(t) and 'H4 bug' = any(t), 'o semanal sai quando há aviso de antes da segunda às 8h, e leva o resto');
  perform ok(exists (select 1 from jsonb_array_elements(l) d where (d->>'registro')::int = 42 and d->>'modo' = 'semanal'
                       and jsonb_array_length(d->'itens') = 2)
             and exists (select 1 from jsonb_array_elements(l) d where (d->>'registro')::int = 42 and d->>'modo' = 'instantaneo'),
             'um envelope por modo');
  perform ok((select d->'itens'->0->>'categoria' from jsonb_array_elements(l) d
               where (d->>'registro')::int = 42 and d->>'modo' = 'semanal') = 'documentos', 'cada item leva a categoria');
  perform ok('B1 bug ontem' = any(t) and 'B2 doc agora' = any(t), 'o diário sai depois das 8h, com o que há');
  perform ok(not ('B3 velho' = any(t)), 'fora da janela do diário (2 dias) não entra');
  perform ok(not ('D1 nunca' = any(t)) and 'D2 teste' = any(t), 'nunca não sai; o teste de e-mail sai');
  perform ok('F1 lembrete' = any(t) and not ('F2 doc agora' = any(t)), 'o lembrete do Studio sai na hora; o semanal novo espera a segunda');
  perform ok(not ('M1 cofre' = any(t)), 'instantâneo com mais de 3 dias não entra');
  perform ok(not ('L1 bloqueada' = any(t)) and not ('K1 egressa' = any(t)), 'conta bloqueada não recebe e-mail');

  select array_agg((i->>'id')::bigint) into ids
    from jsonb_array_elements(l) d, jsonb_array_elements(d->'itens') i;
  perform notificacoes_email_baixa(jsonb_build_object('enviadas', to_jsonb(ids)));
end $$;
do $$
declare t text[]; pu jsonb;
begin
  perform ok(notificacoes_email_lote(200) = '[]'::jsonb, 'depois da baixa, nada repete');

  raise notice 'Notificações por tipo: o push';
  pu := push_lote(300);
  select array_agg(i->>'titulo') into t from jsonb_array_elements(pu) d, jsonb_array_elements(d->'itens') i;
  perform ok(not ('H1 atribuída' = any(t)), 'categoria com push desligado não vai ao aparelho');
  perform ok('H2 studio' = any(t) and 'H4 bug' = any(t), 'as outras vão (o push não depende do e-mail)');
  perform ok(not ('L1 bloqueada' = any(t)), 'conta bloqueada não recebe push');
end $$;

set role authenticated;
do $$
declare pegou boolean := false; n integer;
begin
  raise notice 'Notificações por tipo: RLS';
  perform eu(11, 'x');
  perform ok((select count(*) from notificacao_canais) = 9 and (select count(distinct registro) from notificacao_canais) = 1,
             'cada um lê só as suas');
  begin insert into notificacao_canais (registro, categoria) values (11, 'agenda');
  exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'e não escreve direto');
  perform eu(4, 'admin');
  perform ok((select count(distinct registro) from notificacao_canais) >= 3, 'admin lê todas');
  perform eu(46, 'x');
  perform ok((select count(*) from notificacao_canais) = 0, 'a conta bloqueada não lê nem as suas');
end $$;
reset role;

-- ------------------------------------------------------------
-- Idempotência
-- ------------------------------------------------------------
\ir ../2.18.0_soma.sql
do $$
begin
  raise notice 'Idempotência';
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'rodar de novo mantém uma folha ativa');
  perform ok((select count(*) from pg_indexes where indexname = 'checkin_folhas_ativa_unica') = 1, 'e um índice só');
  perform ok((select count(*) from grupo_papeis) = 3, 'a semente não duplica');
  perform ok((select count(*) from pg_policies where policyname = 'conta_ativa')
             = (select count(*) from pg_class where relnamespace = 'public'::regnamespace and relkind in ('r','p') and relrowsecurity),
             'uma trava por tabela com RLS');
  perform ok((select count(*) from pg_policies where policyname = 'conta_ativa' and permissive = 'RESTRICTIVE'
                 and roles = '{authenticated}') = (select count(*) from pg_policies where policyname = 'conta_ativa'),
             'todas restritivas e só para authenticated');
  perform ok((select (length(d) - length(replace(d, 'tenho_papel(''lideranca'')', ''))) / length('tenho_papel(''lideranca'')') = 1
                from (select pg_get_functiondef('public.doc_gestor()'::regprocedure) d) x), 'doc_gestor trocado uma vez só');
  perform ok(position('papel_atual() in (''admin'',''pessoal'')' in pg_get_functiondef('public.treinamento_gestor()'::regprocedure)) = 0
             and position('eh_gestao()' in pg_get_functiondef('public.treinamento_gestor()'::regprocedure)) > 0, 'treinamento_gestor usa eh_gestao');
  perform ok((select qual from pg_policies where policyname = 'agpred_write') ~ 'eh_gestao', 'a política agpred_write também');
  perform ok((select qual from pg_policies where policyname = 'eroteiros_gestao') ~ 'eh_gestao', 'e eroteiros_gestao');
  perform ok((select count(*) from pg_policies where policyname in ('okr_insert','okr_delete','okrcom_delete','pavisos_select',
                'pavisos_write','pdocs_select','pdocs_write','evtipos_write','siteprj_write','plinks_write','agpred_write',
                'eroteiros_gestao','eprog_ler','doc_emcfg_update','evx_cfg_update','doc_emit_select')
                and coalesce(qual, with_check) ~ 'eh_gestao' and coalesce(qual, '') !~ 'papel_atual'
                and coalesce(with_check, '') !~ 'papel_atual') = 16, 'as 16 políticas da lista, sem sobra de papel_atual');
  perform ok((select qual from pg_policies where policyname = 'pavisos_select') ~ 'publicado', 'e o resto da condição continua lá');
  perform ok((select count(*) from atividade_quadros) >= 1, 'os espelhos ficam');
  perform ok((select count(*) from notificacao_canais where registro = 11) = 9
             and (select count(*) from notificacao_canais where registro = 42) = 2
             and not exists (select 1 from notificacao_canais where registro = 40), 'as preferências não são migradas de novo');
  perform eu(42, 'x');
  perform ok(meu_nivel_no_grupo(gid('Gestão')) = 'leitura' and eh_comite(), 'e as regras continuam');
end $$;
\echo '2.18.0: tudo certo'
