\set ON_ERROR_STOP on
\pset pager off
-- ============================================================
-- Teste da 2.18.0 — por enquanto, a folha única de check-in.
-- Rode num banco com o esqueleto e o de Storage (auth.uid); o teste
-- aplica a 29.0 e a 2.18.0 (e a 2.18.0 de novo, no fim).
-- ============================================================
create or replace function ok(cond boolean, txt text) returns void language plpgsql as $$
begin
  if cond then raise notice '  ok   %', txt;
  else raise exception 'FALHOU: %', txt; end if;
end $$;
create or replace function eu(p_reg integer, p_papel text) returns void language plpgsql as $$
begin
  perform set_config('teste.registro', coalesce(p_reg::text, ''), false);
  perform set_config('teste.papel', p_papel, false);
  perform set_config('teste.uid', coalesce((select id::text from perfis where registro = p_reg), ''), false);
end $$;

create table if not exists presencas (id bigint generated by default as identity primary key,
  registro integer not null, registrado_em timestamptz not null default now());
insert into perfis (id, email, papel, registro) values
  (gen_random_uuid(), 'ana@nro.dev', 'admin', 4), (gen_random_uuid(), 'bruno@nro.dev', 'leitura', 11),
  (gen_random_uuid(), 'carla@nro.dev', 'pessoal', 17)
on conflict do nothing;

\ir ../v29_presenca_e_inicio.sql

-- duas folhas ativas, como a 29.0 permitia
select eu(4, 'admin');
insert into checkin_folhas (rotulo, criada_por) values ('Porta', 'x'), ('Recepção', 'x');

\ir ../2.18.0_soma.sql

do $$
declare r jsonb; v_a uuid; v_b uuid; v_tok_a uuid; v_tok_b uuid;
begin
  raise notice 'Check-in: folha única';
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'a migração deixou uma folha ativa só');
  perform ok((select rotulo from checkin_folhas where revogada_em is null) = 'Recepção', 'a mais recente');

  perform eu(11, 'leitura');
  perform ok(checkin_folha_criar('x')->>'status' = 'sem_permissao', 'quem é leitura não gera');
  perform eu(17, 'pessoal');
  perform ok(checkin_folha_criar('x')->>'status' = 'sem_permissao', 'o Depto. de Pessoal também não gera');
  perform ok(checkin_folha_revogar(gen_random_uuid())->>'status' = 'sem_permissao', 'nem revoga');

  perform eu(4, 'admin');
  select token into v_tok_a from checkin_folhas where revogada_em is null;
  r := checkin_folha_criar('Entrada');
  perform ok(r->>'status' = 'ok' and r->>'token' is not null, 'admin gera e recebe o token');
  v_b := (r->>'id')::uuid; v_tok_b := (r->>'token')::uuid;
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'continua uma só ativa');
  perform ok((select revogada_em is null from checkin_folhas where id = v_b), 'a nova é a ativa');
  perform ok((select revogada_motivo from checkin_folhas where token = v_tok_a) = 'substituída', 'a anterior foi invalidada');
  perform ok((select baixada_em is not null and baixada_por is not null from checkin_folhas where id = v_b), 'o download fica registrado');

  perform eu(11, 'leitura');
  perform ok(registrar_checkin_folha(v_tok_a)->>'status' = 'folha_invalida', 'o QR antigo é recusado');
  perform ok(registrar_checkin_folha(v_tok_b)->>'status' = 'ok', 'o QR novo registra');

  perform eu(4, 'admin');
  perform ok(checkin_folha_revogar(v_b)->>'status' = 'ok', 'admin revoga a ativa');
  perform ok(checkin_folha_criar('Depois')->>'status' = 'ok', 'e gera outra depois');
end $$;

-- RLS: o token não é legível
do $$ declare t text; begin
  for t in select tablename from pg_tables where schemaname = 'public' and tablename <> 'checkin_folhas' loop
    execute format('grant select on public.%I to authenticated', t); end loop; end $$;
set role authenticated;
do $$
declare pegou boolean := false; n integer;
begin
  perform eu(4, 'admin');
  begin perform token from checkin_folhas limit 1;
  exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'o token não é legível por select, nem para admin');
  select count(*) into n from (select id, numero, rotulo, usos from checkin_folhas) x;
  perform ok(n >= 3, 'a lista (sem token) é legível');
  pegou := false;
  begin insert into checkin_folhas (rotulo) values ('direto');
  exception when insufficient_privilege then pegou := true; end;
  perform ok(pegou, 'ninguém insere folha direto');
end $$;
reset role;

-- idempotência
\ir ../2.18.0_soma.sql
do $$
begin
  perform ok((select count(*) from checkin_folhas where revogada_em is null) = 1, 'rodar de novo mantém uma folha ativa');
  perform ok((select count(*) from pg_indexes where indexname = 'checkin_folhas_ativa_unica') = 1, 'e um índice só');
end $$;
\echo '2.18.0: tudo certo'
